/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2;

import javax.swing.JFrame;

/**
 * Crea la ventana donde se mostrarán los recorridos una vez insertada la
 * expresión
 *
 * @author digio
 */
public class Window extends javax.swing.JFrame {

    Funciones f = new Funciones();
    Conversion c = new Conversion();

    public Window() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        postfijo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        infijo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        prefijo = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Infijo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel2.setText("Polaca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel3.setText("Polaca Inversa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        postfijo.setColumns(20);
        postfijo.setRows(5);
        jScrollPane1.setViewportView(postfijo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 370, 60));

        infijo.setColumns(20);
        infijo.setRows(5);
        jScrollPane2.setViewportView(infijo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 370, 60));

        prefijo.setColumns(20);
        prefijo.setRows(5);
        jScrollPane3.setViewportView(prefijo);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 370, 60));

        jButton2.setText("Insertar Expresion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 410, -1));

        jLabel4.setText("Arbol de Expresion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ListaSimple expression = f.Leer_txt();

        String cadena = "";
        String ref = "";
        String temp = "";
        Nodo aux = expression.getpFirst();
        ListaSimple lista = new ListaSimple();
        Nodo aux2 = lista.getpFirst();

        if (expression.Notacion().equals("Infija")) {

            for (int i = 0; i < expression.getSize(); i++) {
                cadena += aux.getDato();
                aux = aux.getPnext();
            }

            ref = c.covertInfixToPostfix(cadena);

            for (int i = 0; i < ref.length(); i++) {
                lista.InsertarFinal(ref.charAt(i));
            }

        } else if (expression.Notacion().equals("Polaca")) {
            for (int i = 0; i < expression.getSize(); i++) {
                cadena += aux.getDato();
                aux = aux.getPnext();
            }

            ref = c.convertPrefixToInfix(cadena);
            temp = c.covertInfixToPostfix(ref);

            for (int i = 0; i < temp.length(); i++) {
                lista.InsertarFinal(temp.charAt(i));
            }
        } else if (expression.Notacion().equals("Polaca Inversa")) {

            lista = expression;
        }

        ArbolBinario arbolExpresion = lista.conversionPosfijaEnArbol();
        Lienzo objLienzo = new Lienzo(); //VISTA
        Controlador objControlador = new Controlador(objLienzo, arbolExpresion); //CONTROLADOR

        objControlador.iniciar();
        //= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
        //MOSTRAR LIENZO EN UNA VENTANA TODO
        JFrame ventana = new JFrame();
        ventana.getContentPane().add(objLienzo);
        ventana.setDefaultCloseOperation(3);
        ventana.setSize(3000, 800);
        ventana.setVisible(true);
        //= = = = = = = = 

        infijo.setText(arbolExpresion.inorden(arbolExpresion.getNodoRaiz()));
        prefijo.setText(arbolExpresion.preorden(arbolExpresion.getNodoRaiz()));
        postfijo.setText(arbolExpresion.postorden(arbolExpresion.getNodoRaiz()));

        this.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infijo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea postfijo;
    private javax.swing.JTextArea prefijo;
    // End of variables declaration//GEN-END:variables
}
